### ISSUE TITLE
Things installed with `upcast install` can be garbage collected by nix

### ISSUE THREAD

**Issue by soenkehahn** [zalora/upcast#37] opened 2015-03-09 06:00 UTC
If you install some executable with
```bash
upcast install --target host --profile foo /nix/store/...
```
then unfortunately running
```bash
nix-collect-garbage -d
```
on the host will result in those executables being deleted from the store and the links (`~/foo/bin/...`) pointing nowhere.

**Comment by proger** [comment] 2015-03-09 06:05
@soenkehahn what if you try to install in `/nix/var/nix/profiles/foo` ?

**Comment by soenkehahn** [comment] 2015-03-09 06:10
@proger: Then the store paths won't be deleted.

**Comment by proger** [comment] 2015-03-09 07:08
I think you should use `/nix/var/nix/profiles` as a profile root in this case.

`nix-env`'s  man page says:
```
       --profile, -p
           Specifies the profile to be used by those operations that operate on a profile (designated below as the
           active profile). A profile is a sequence of user environments called generations, one of which is the
           current generation.
```

and `/nix/var/nix/profiles` is the convention that nix uses for all GC roots.

**Comment by jekor** [comment] 2015-06-24 07:05
I don't see this as a bug, but we could provide a default profile to use so that it behaves more as new users would expect. Is there any reason not to use new default profiles (what `nix-env -i` does) to provide intuitive behavior that also allows rollback with nix commands?

**Comment by proger** [comment] 2015-06-24 17:49
Actually any profile supports rollbacks, except nix GC only tracks paths in `/nix/var/nix/profiles`. However I'd make `-p` in upcast imply `/nix/var/nix/profiles/` as a prefix to a profile name unless it's specified as an absolute path.

**Comment by shlevy** [comment] 2015-06-24 17:50
IMO this should be nix default

**Comment by proger** [comment] 2015-07-21 05:16
Ok, closing as not a bug.

**Closed by proger** 2015-07-21 05:16 UTC
Labels: bug
