### ISSUE TITLE
Failure parsing StatusType from "initializing"

### ISSUE THREAD

**Issue by phunehehe** [zalora/upcast#50] opened 2015-08-21 03:46 UTC
Looking like a missing status
> upcast: SerializerError "EC2" "Failed reading: Failure parsing StatusType from \"initializing\""

**Comment by proger** [comment] 2015-08-21 05:46
Thanks. There's a high chance #48 fixes it.

**Comment by proger** [comment] 2015-09-11 18:14
Closing with lack of reproducibility since #48.

**Closed by proger** 2015-09-11 18:14 UTC
